
spring:
  application:
    name: gateway-service
  cloud:

   gateway:
     routes:
#----------Member-------------------
       - id: member-service
         uri: http://localhost:8081
         predicates:
           - Path=/api/member/**

#----------Security------------------
       - id: security-service
         uri: http://localhost:8082
         predicates:
           - Path=/api/keycloak/**

#------------Payment------------------
       - id: paiement-service
         uri: http://localhost:8083
         predicates:
           - Path=/api/payment/**

#-----------Forum---------------------
       - id: forum-service
         uri: http://localhost:8084
         predicates:
           - Path=/api/forum/**
#-----------Ged---------------------
       - id: Ged_Service
         uri: http://localhost:8088
         predicates:
           - Path=/api/file/**

#-----------Project-------------------
       - id: project-service
         uri: http://localhost:8091
         predicates:
           - Path=/api/project/**

#-----------Cours---------------------
       - id: cours-service
         uri: http://localhost:8090
         predicates:
           - Path=/api/cours/**

#-----------Evaluation---------------------
       - id: evaluation-service
         uri: http://localhost:8094
         predicates:
           - Path=/api/evaluation/**

#-----------mail---------------------
       - id: Email_Service
         uri: http://localhost:8086
         predicates:
           - Path=/api/mail/**
#-----------Notification---------------------
       - id: notification-service
         uri: http://localhost:8085
         predicates:
           - Path=/api/**



     default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Origin
     globalcors:
      cors-configurations:
        '[/**]':
          allowedOrigins: "*"
          allowedMethods: "*"
          allowedHeaders: "*"

    gateway:
      routes:
        #----------Member-------------------
        - id: member-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/member/**

        #----------mail-------------------
        - id: member-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/mail/**

        #----------Security------------------
        - id: security-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/keycloak/**

        #------------Payment------------------
        - id: paiement-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/payment/**

        #-----------Forum---------------------
        - id: forum-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/forum/**

        #-----------Project-------------------
        - id: project-service
          uri: http://localhost:8091
          predicates:
            - Path=/api/project/**

        #-----------Cours---------------------
        - id: cours-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/cours/**

        #-----------notification-service---------------------
        - id: notification-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/**

        #-----------Evaluation---------------------
        - id: evaluation-service
          uri: http://localhost:8094
          predicates:
            - Path=/api/evaluation/**
        #-----------GED---------------------
        - id: Ged_Service
          uri: http://localhost:8088
          predicates:
            - Path=/api/**




      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"







