spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        #----------Member-------------------
        - id: member-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/member/**

        #----------mail-------------------
        - id: Email-Service
          uri: http://localhost:8086
          predicates:
            - Path=/api/mail/**

        #----------Security------------------
        - id: security-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/keycloak/**

        #------------Payment------------------
        - id: paiement-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/payment/**

        #-----------Forum---------------------
        - id: forum-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/forum/**

        #-----------Project-------------------
        - id: project-service
          uri: http://localhost:8091
          predicates:
            - Path=/api/project/**

        #-----------Cours---------------------
        - id: cours-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/cours/**

        #-----------Ged---------------------
        - id: Ged-Service
          uri: http://localhost:8088
          predicates:
            - Path=/api/**
        #-----------notification-service------
        - id: notification-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/**
        #-----------eval---------------------
        - id: evaluation-service
          uri: http://localhost:8094
          predicates:
            - Path=/api/**




      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"